#!/bin/sh

if [ "${PYPEDIR-0}" = "0" ]; then
  echo "`basename $0`: set \$PYPEDIR first."
  exit 1
fi

export WHO=`/usr/bin/whoami`
export PYTHONEXE=$(which python)

libdir=$(${PYTHONEXE} -c "from distutils.sysconfig import get_python_lib; \
		print(get_python_lib())" | xargs dirname)
incdir=$(${PYTHONEXE} -c "from distutils.sysconfig import get_python_lib; \
		print(get_python_lib())" | sed s/lib/include/g | xargs dirname)
export PYTHONINC=$incdir
export PYCOMPILE=$libdir/compileall.py



/usr/bin/make -f Buildfile $*
