#!/bin/sh

if [ "${PYPEDIR-0}" = "0" ]; then
  echo "`basename $0`: set \$PYPEDIR first."
  exit 1
fi

export PYTHONEXE=$(which python)

if [ -d /usr/include/python2.7 ]; then
  export PYTHONINC=$(ls -d /usr/include/python2.7 | sort | tail -1)
  export PYCOMPILE=$(ls -d /usr/lib/python2.7 | sort | tail -1)/compileall.py
else
  pydir=$(dirname $(dirname ${PYTHONEXE}))
  export PYTHONINC=$pydir/include
  export PYCOMPILE=$pydir/lib/python2.7/compileall.py
fi

export WHO=`/usr/bin/whoami`

/usr/bin/make -f Buildfile $*
