#!/bin/sh
#
# Install for mazer lab -- this ensures that a global build and install
# takes place on an ubuntu 10.04.4 machine in the lab. 10.04.4 binaries
# pretty much work on everything in the lab including debian/mint systems.
#

grep -q 10.04.4 /etc/issue
if [ $? -ne 0 ]; then
 echo "Wrong arch -- running on udon..."
 ssh -t udon "(cd /auto/share/src/pype3; ./install_mlab $*)"
else
  if [ "$*" = "" ]; then
    sudo -p"sudo [mlab install]: " \
	./install_private /auto/share/pype3/`uname -m` clobber install docs
  else
    sudo -p"mlab [mlab install]: " \
	./install_private /auto/share/pype3/`uname -m` $*
  fi
fi
