#!/bin/bash
#
# Install for mazer lab
#

DEST=/auto/share/pype3/`uname -m`

if [ "$*" = "" ]; then
    sudo -p"sudo [mlab install]: " ./install-to $DEST clobber install docs
elif [[ "$1" =~ (.*nd.*|.*nodo.*) ]]; then
    #anything like -nodocs, -nd, nd etc will install WITHOUT docs
    sudo -p"sudo [mlab install]: " ./install-to $DEST clobber install
else
    sudo -p"mlab [mlab install]: " ./install-to $DEST $*
fi
