OBJS = main.o  trial.o  trials.o
EYELINK_LIB=../../../lib
EYELINK_INCLUDE=../../../include
LINKLIBS=-L$(EYELINK_LIB) -leyelink_core_graphics  -leyelink_core -lsdl_util `sdl-config --libs`   -lSDL_ttf -lSDL_gfx -lSDL_mixer -lrt
CFLAGS=-I$(EYELINK_INCLUDE)
text: $(OBJS)
	$(CC) -o text $(OBJS) $(LINKLIBS)
clean:
	-rm -rf $(OBJS) text
