#!/bin/sh
# usage: install $PYPEDIR

dest=$1

# copy .sh scripts to p2mdir and make executable (strip .sh)
for i in *.sh; do
  ii=`echo $i | sed s/.sh$//g`
  cp $i $dest/$ii
  chmod +x $dest/$ii
done

# copy .py scripts to p2mdir and make executable (strip .py)
for i in pype_expander.py pype_count.py matlab-nh.py \
    p2mupdate.py pypeinfo.py showpypefile.py showparams.py ; do
  ii=`echo $i | sed s/.py$//g`

  # .py and non-.py file are required so pypenv can import as module!!
  cp $i $dest/$i
  ln -sf $dest/$i $dest/$ii
  chmod +x $dest/$ii
done

ln -sf $dest/showpypefile.py $dest/pf


		 

