OBJS = grid_bitmap.o  main.o  regions.o  trial.o  trials.o
EYELINK_LIB=../../../lib
EYELINK_INCLUDE=../../../include
LINKLIBS=-L$(EYELINK_LIB) -leyelink_core -leyelink_core_graphics  -lsdl_util `sdl-config --libs`  -lSDL_mixer -lrt
CFLAGS=-I$(EYELINK_INCLUDE)
control: $(OBJS)
	$(CC) -o control $(OBJS) $(LINKLIBS)
clean:
	-rm -rf $(OBJS) control
