#!/bin/sh

cat <<EOF
# -*- Mode: Python; tab-width: 4; py-indent-offset: 4; -*-

"""Version and compilation info.

Autogenerated file -- **DO NOT USE DIRECTLY**

This file is automatically generated during the build process. Changes
will be lost on the next build.
"""

PypeVersion = "3.0"
EOF

echo "PypeBuildDir = \"`pwd`\""
echo "PypeBuildBy = \"$LOGNAME\""
echo "PypeBuildDate = \"`date`\""
echo "PypeBuildHost = \"`hostname`\""

# dump subversion info if available
if /usr/bin/svn info 1>/dev/null 2>/dev/null; then
  # use svn, if available
  echo 'PypeVersionInfo = """'
  svn info
  echo '"""'
  echo 'PypeVersionID = """svn:r'`svnversion`'"""'
elif git log -n1 1>/dev/null 2>/dev/null; then
  # dump git info if available
  echo 'PypeVersionInfo = """'
  (git log -n1 >/tmp/$$.log; cat /tmp/$$.log; rm /tmp/$$.log)
  echo '"""'
  echo 'PypeVersionID = """git:'`git rev-list --max-count=1 HEAD`'"""'
else
  # no version control info available..
  echo 'PypeVersionInfo = ""'
  echo 'PypeVersionID = ""'
fi



